# -*- coding: utf-8 -*-
"""Project Gutenberg text cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vghjehj6w615d9VY5huDRmRIB-OJd-yL
"""

"""
Corpus Reformatter — Paragraph to One-Sentence-Per-Line (v3)
=======================================================================
Fixes from v2:
  - Multi-line sentences (broken across lines in the original file)
    are now flattened into ONE line before sentence splitting
  - Apostrophes are preserved (mom's, don't, it's etc stay intact)
    while all other special characters are still removed

What it does:
  - Wherever there was a sentence boundary (. ! ?), a NEW LINE starts
  - The punctuation itself is removed
  - Apostrophes kept, everything else special-char removed
  - Lowercase
  - Multiple files combined into a single output

Use this BEFORE training — feed the output into your
LSTM/Transformer training script as CORPUS_FILE.
"""

import re
from pathlib import Path
from google.colab import files

print("Upload your corpus .txt file(s) — multiple files supported")
uploaded = files.upload()

if not uploaded:
    print("[!] No file uploaded.")

else:
    all_lines = []

    for filename, content in uploaded.items():
        print(f"\nProcessing: {filename}")
        text = content.decode('utf-8', errors='ignore')
        print(f"  Raw chars : {len(text):,}")

        # ── Step 1: Flatten — join lines that are actually the
        # same sentence broken across multiple lines in the source file.
        # Single newlines become spaces; only a BLANK line (paragraph
        # break) is treated as a real separator.
        text = re.sub(r'\n{2,}', '<PARA>', text)   # mark real paragraph breaks
        text = text.replace('\n', ' ')              # flatten remaining line breaks
        text = text.replace('<PARA>', ' ')           # paragraph breaks become spaces too —
                                                       # sentence splitting below handles boundaries

        # ── Step 2: Split into sentences wherever . ! ? appears
        sentences = re.findall(r"[^.!?]+[.!?]?", text)

        file_lines = []
        for sent in sentences:
            sent = sent.lower()

            sent = re.sub(r'\d+', '', sent)

            sent = re.sub(r"[^a-z\s'.,?!]", '', sent)

            sent = re.sub(r'([.,?!])', r' \1 ', sent)

            sent = re.sub(r"\s+'", ' ', sent)
            sent = re.sub(r"'\s+", ' ', sent)
            sent = re.sub(r"''+", "'", sent)

            sent = re.sub(r'\s+', ' ', sent).strip()

            if len(sent.split()) >= 4:
                file_lines.append(sent)

        print(f"  Sentences extracted : {len(file_lines):,}")
        all_lines.extend(file_lines)

    # Combine + dedup across ALL files
    unique = list(dict.fromkeys(all_lines))
    total_words = sum(len(l.split()) for l in unique)

    print(f"\n{'='*50}")
    print(f"Files processed  : {len(uploaded)}")
    print(f"Total sentences  : {len(unique):,}")
    print(f"Total words      : {total_words:,}")
    print(f"Avg words/line   : {total_words/max(len(unique),1):.1f}")

    print(f"\nData quality:")
    if total_words < 100000:
        print(f"  ⚠  {total_words:,} words — too low, add more books")
    elif total_words < 500000:
        print(f"  ~  {total_words:,} words — okay, 3-4 more books recommended")
    elif total_words < 2000000:
        print(f"  ✓  {total_words:,} words — good for training")
    else:
        print(f"  ✓✓ {total_words:,} words — excellent!")

    print(f"\nSample output:")
    for l in unique[:6]:
        print(f"  • {l}")

    # Save — ONE combined file for all uploaded files
    OUTPUT_FILE = "corpus_lines.txt"
    Path(OUTPUT_FILE).write_text('\n'.join(unique), encoding='utf-8')

    files.download(OUTPUT_FILE)
    print(f"\n✓ Download started: {OUTPUT_FILE}")