# -*- coding: utf-8 -*-
"""english_Transformer_train_2.7M_V4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mt5GwmSVlJZSQO81SR-wD-2bMU0y7Di5
"""

!pip install tensorflow

from google.colab import drive
drive.mount('/content/drive')

"""
English Next Word Prediction — Transformer (GPT-style) v5
=============================================================
FIX from v4: Keras built-in Tokenizer splits apostrophe-words
inconsistently — "don't" became "do" + "'", "it's" became
"i" + "'s". This polluted the vocab with junk single-letter
tokens, which is why generation produced gibberish like
"o ce by a y o e".

Fix: custom regex-based tokenizer (SimpleWordTokenizer below)
that treats apostrophe-words as ONE token, always:
    "don't" -> "don't"   (single token, never split)
    "mom's" -> "mom's"   (single token, never split)

Everything else (model, training loop) stays the same as v4.

Install:
    !pip install tensorflow
"""

import os
import re
import json
import pickle
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from collections import Counter

# ════════════════════════════════════════════════════
#  CONFIG
# ════════════════════════════════════════════════════
CORPUS_FILE      = "/content/drive/MyDrive/english_corpus_2.7M_word.txt.txt"
SAVE_DIR         = "/content/drive/MyDrive/english_transformer_2.7M_V5/"

VOCAB_SIZE       = 12000
SEQ_LEN          = 16
EMBED_DIM        = 128
NUM_HEADS        = 4
NUM_LAYERS       = 2
FF_DIM           = 384
DROPOUT_RATE     = 0.2
BATCH_SIZE       = 256
EPOCHS           = 60
VALIDATION_SPLIT = 0.1
# ════════════════════════════════════════════════════

import tensorflow as tf
from tensorflow.keras import layers, Model, callbacks
from tensorflow.keras.preprocessing.sequence import pad_sequences

print(f"TensorFlow  : {tf.__version__}")
print(f"GPU         : {tf.config.list_physical_devices('GPU')}")

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    tf.config.experimental.set_memory_growth(gpus[0], True)

tf.keras.mixed_precision.set_global_policy('mixed_float16')
print(f"Mixed precision : {tf.keras.mixed_precision.global_policy().name}")


# ════════════════════════════════════════════════════
#  CUSTOM TOKENIZER — fixes apostrophe splitting bug
# ════════════════════════════════════════════════════
class SimpleWordTokenizer:
    """
    Drop-in replacement for Keras Tokenizer that NEVER splits
    apostrophe-words. "don't" and "mom's" are always single tokens.

    Provides the same interface used downstream:
        .fit_on_texts(lines)
        .texts_to_sequences(lines)
        .word_index   (dict: word -> id)
        .index_word    (dict: id -> word)
    """
    # Matches a run of letters, optionally followed by an
    # apostrophe + more letters — e.g. "don't", "mom's", "y'all"
    WORD_RE = re.compile(r"[a-z]+(?:'[a-z]+)?")

    def __init__(self, num_words=None, oov_token='<OOV>'):
        self.num_words  = num_words
        self.oov_token  = oov_token
        self.word_index = {}
        self.index_word = {}
        self.word_counts = {}

    def _tokenize(self, text):
        return self.WORD_RE.findall(text.lower())

    def fit_on_texts(self, lines):
        counter = Counter()
        for line in lines:
            counter.update(self._tokenize(line))

        self.word_counts = dict(counter)

        # Reserve index 0 for padding, 1 for OOV
        self.word_index = {self.oov_token: 1}
        self.index_word = {1: self.oov_token}

        most_common = counter.most_common(
            None if self.num_words is None else self.num_words - 2
        )
        for i, (word, _) in enumerate(most_common, start=2):
            self.word_index[word] = i
            self.index_word[i]    = word

    def texts_to_sequences(self, lines):
        oov_id = self.word_index.get(self.oov_token, 1)
        limit  = self.num_words if self.num_words else len(self.word_index) + 2
        out = []
        for line in lines:
            tokens = self._tokenize(line)
            ids = [
                self.word_index.get(t, oov_id) if self.word_index.get(t, oov_id) < limit
                else oov_id
                for t in tokens
            ]
            out.append(ids)
        return out


# ════════════════════════════════════════════════════
#  STEP 1 — LOAD CORPUS
# ════════════════════════════════════════════════════
def load_corpus(path):
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"\n[!] File not found: {path}")

    lines = [l.strip() for l in p.read_text(encoding='utf-8').splitlines()
             if l.strip() and len(l.strip().split()) >= 4]

    total_words = sum(len(l.split()) for l in lines)
    print(f"\n{'='*52}")
    print(f"STEP 1: CORPUS")
    print(f"{'='*52}")
    print(f"  Sentences    : {len(lines):,}")
    print(f"  Total words  : {total_words:,}")
    print(f"  Avg length   : {total_words/max(len(lines),1):.1f} words/sentence")

    print(f"\n  Sample lines:")
    for l in lines[:3]:
        print(f"    • {l[:80]}")
    return lines


# ════════════════════════════════════════════════════
#  STEP 2 — TOKENIZE (custom, apostrophe-safe)
# ════════════════════════════════════════════════════
def build_tokenizer(lines, vocab_size):
    tok = SimpleWordTokenizer(num_words=vocab_size, oov_token='<OOV>')
    tok.fit_on_texts(lines)
    actual_vocab = min(vocab_size, len(tok.word_index) + 1)

    print(f"\n{'='*52}")
    print(f"STEP 2: TOKENIZATION")
    print(f"{'='*52}")
    print(f"  Unique words  : {len(tok.word_index):,}")
    print(f"  Vocab used    : {actual_vocab:,}")

    # Sanity check — confirm apostrophe words survive intact
    apostrophe_words = [w for w in tok.word_index if "'" in w][:10]
    print(f"  Apostrophe words preserved (sample): {apostrophe_words}")

    return tok, actual_vocab


# ════════════════════════════════════════════════════
#  STEP 3 — SEQUENCES
# ════════════════════════════════════════════════════
def create_sequences(lines, tokenizer, seq_len):
    X_list, y_list = [], []
    oov_id  = tokenizer.word_index.get('<OOV>', 1)
    skipped = 0

    sequences = tokenizer.texts_to_sequences(lines)

    for ids in sequences:
        if not ids or len(ids) < seq_len + 1:
            skipped += 1
            continue
        if ids.count(oov_id) / len(ids) > 0.30:
            skipped += 1
            continue
        for i in range(seq_len, len(ids)):
            X_list.append(ids[i - seq_len : i])
            y_list.append(ids[i])

    X = np.array(X_list, dtype=np.int32)
    y = np.array(y_list, dtype=np.int32)

    ram_mb = (X.nbytes + y.nbytes) / 1e6
    print(f"\n{'='*52}")
    print(f"STEP 3: SEQUENCES")
    print(f"{'='*52}")
    print(f"  Sequences     : {len(X):,}")
    print(f"  Skipped lines : {skipped:,}")
    print(f"  X shape       : {X.shape}")
    print(f"  RAM used      : ~{ram_mb:.1f} MB ✓")
    return X, y


# ════════════════════════════════════════════════════
#  STEP 4 — TRANSFORMER MODEL (unchanged from v2)
# ════════════════════════════════════════════════════
class PositionalEmbedding(layers.Layer):
    def __init__(self, seq_len, vocab_size, embed_dim, **kwargs):
        super().__init__(**kwargs)
        self.seq_len    = seq_len
        self.vocab_size = vocab_size
        self.embed_dim  = embed_dim
        self.token_emb  = layers.Embedding(vocab_size, embed_dim, mask_zero=True)
        self.pos_emb    = layers.Embedding(seq_len, embed_dim)

    def call(self, x):
        positions = tf.range(start=0, limit=tf.shape(x)[-1], delta=1)
        return self.token_emb(x) + self.pos_emb(positions)

    def compute_mask(self, inputs, mask=None):
        return self.token_emb.compute_mask(inputs)

    def get_config(self):
        cfg = super().get_config()
        cfg.update({'seq_len': self.seq_len, 'vocab_size': self.vocab_size,
                    'embed_dim': self.embed_dim})
        return cfg


class TransformerBlock(layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, dropout, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.ff_dim    = ff_dim
        self.dropout   = dropout

        self.att  = layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim // num_heads)
        self.ffn  = tf.keras.Sequential([
            layers.Dense(ff_dim, activation='gelu'),
            layers.Dense(embed_dim),
        ])
        self.norm1 = layers.LayerNormalization(epsilon=1e-6)
        self.norm2 = layers.LayerNormalization(epsilon=1e-6)
        self.drop1 = layers.Dropout(dropout)
        self.drop2 = layers.Dropout(dropout)

    def call(self, x, training=False):
        seq_len = tf.shape(x)[1]
        causal_mask = tf.linalg.band_part(tf.ones((seq_len, seq_len)), -1, 0)
        causal_mask = tf.cast(causal_mask, tf.bool)

        attn_out = self.att(x, x, attention_mask=causal_mask, training=training)
        x = self.norm1(x + self.drop1(attn_out, training=training))

        ffn_out = self.ffn(x)
        x = self.norm2(x + self.drop2(ffn_out, training=training))
        return x

    def get_config(self):
        cfg = super().get_config()
        cfg.update({'embed_dim': self.embed_dim, 'num_heads': self.num_heads,
                    'ff_dim': self.ff_dim, 'dropout': self.dropout})
        return cfg


class LastToken(layers.Layer):
    """Picks the last timestep's representation from a sequence.
    A named custom layer instead of a raw Lambda — Lambda layers
    with Python functions are blocked from safe deserialization by
    Keras when the saved model is reloaded elsewhere (e.g. in a
    Flask app), so this is required for the model to load later."""
    def call(self, x):
        return x[:, -1, :]

    def get_config(self):
        return super().get_config()


def build_model(vocab_size, seq_len, embed_dim, num_heads, num_layers, ff_dim, dropout):
    inp = layers.Input(shape=(seq_len,), name='input')
    x = PositionalEmbedding(seq_len, vocab_size, embed_dim, name='pos_embedding')(inp)
    x = layers.Dropout(dropout)(x)

    for i in range(num_layers):
        x = TransformerBlock(embed_dim, num_heads, ff_dim, dropout,
                             name=f'transformer_block_{i}')(x)

    x = LastToken(name='last_token')(x)
    x = layers.Dense(embed_dim, activation='gelu', name='proj')(x)
    x = layers.Dropout(dropout)(x)
    out = layers.Dense(vocab_size, activation='softmax', dtype='float32', name='output')(x)

    return Model(inputs=inp, outputs=out)


# ════════════════════════════════════════════════════
#  STEP 5 — TRAIN
# ════════════════════════════════════════════════════
def get_callbacks(save_dir):
    os.makedirs(save_dir, exist_ok=True)
    return [
        callbacks.EarlyStopping(monitor='val_loss', patience=5,
                                restore_best_weights=True, verbose=1),
        callbacks.ModelCheckpoint(filepath=os.path.join(save_dir, 'best_model.keras'),
                                  monitor='val_loss', save_best_only=True, verbose=1),
        callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                                    patience=2, min_lr=1e-6, verbose=1),
        callbacks.CSVLogger(os.path.join(save_dir, 'training_log.csv')),
    ]


def plot_history(history, save_dir):
    fig, ax = plt.subplots(1, 2, figsize=(13, 4))
    ax[0].plot(history.history['loss'],     label='Train Loss', color='#5b6ef5')
    ax[0].plot(history.history['val_loss'], label='Val Loss',   color='#38d9a9')
    ax[0].set_title('Loss'); ax[0].set_xlabel('Epoch'); ax[0].legend(); ax[0].grid(alpha=.3)

    ax[1].plot(history.history['accuracy'],     label='Train Acc', color='#5b6ef5')
    ax[1].plot(history.history['val_accuracy'], label='Val Acc',   color='#38d9a9')
    ax[1].set_title('Accuracy'); ax[1].set_xlabel('Epoch'); ax[1].legend(); ax[1].grid(alpha=.3)

    plt.tight_layout()
    path = os.path.join(save_dir, 'training_plot.png')
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"  Plot saved : {path}")


# ════════════════════════════════════════════════════
#  STEP 6 — INFERENCE
# ════════════════════════════════════════════════════
def predict_next(model, tokenizer, seed_text, seq_len, top_k=5, temperature=0.8):
    ids   = tokenizer.texts_to_sequences([seed_text])[0][-seq_len:]
    ids   = pad_sequences([ids], maxlen=seq_len, padding='pre')
    probs = model.predict(ids, verbose=0)[0].astype('float64')

    probs = np.log(probs + 1e-10) / temperature
    probs = np.exp(probs)
    probs /= probs.sum()

    top   = np.argsort(probs)[::-1]
    top   = [i for i in top if i > 1][:top_k]

    return [(tokenizer.index_word.get(i, '?'), round(float(probs[i]), 4)) for i in top]


def generate_text(model, tokenizer, seed_text, seq_len, max_words=25, temperature=0.8):
    text = seed_text
    for _ in range(max_words):
        ids = tokenizer.texts_to_sequences([text])[0][-seq_len:]
        ids = pad_sequences([ids], maxlen=seq_len, padding='pre')

        probs = model.predict(ids, verbose=0)[0]
        probs = np.log(probs + 1e-10) / temperature
        probs = np.exp(probs)
        probs /= probs.sum()

        next_id = np.random.choice(len(probs), p=probs)
        if next_id <= 1:
            continue

        word = tokenizer.index_word.get(next_id)
        if word:
            text += " " + word
    return text


def inference_demo(model, tokenizer, seq_len):
    test_phrases = [
        "it was the best of",
        "she looked at him and",
        "the sun was setting over",
        "he could not believe what",
        "they walked together through the",
        "i don't know what",
    ]
    print(f"\n{'='*52}")
    print(f"INFERENCE DEMO — Top 5 next-word predictions")
    print(f"{'='*52}")
    for phrase in test_phrases:
        preds = predict_next(model, tokenizer, phrase, seq_len, top_k=5, temperature=0.8)
        pstr  = "  |  ".join(f"{w} ({p})" for w, p in preds)
        print(f"\n  Input : '{phrase}'")
        print(f"  →  {pstr}")

    print(f"\n{'='*52}")
    print(f"TEXT GENERATION DEMO")
    print(f"{'='*52}")
    seed = "it was the best of"
    generated = generate_text(model, tokenizer, seed, seq_len, max_words=25, temperature=0.8)
    print(f"\n  Seed      : {seed}")
    print(f"  Generated : {generated}")


# ════════════════════════════════════════════════════
#  MAIN
# ════════════════════════════════════════════════════
def main():
    os.makedirs(SAVE_DIR, exist_ok=True)

    lines = load_corpus(CORPUS_FILE)
    tokenizer, actual_vocab = build_tokenizer(lines, VOCAB_SIZE)

    tok_path = os.path.join(SAVE_DIR, 'tokenizer.pkl')
    with open(tok_path, 'wb') as f:
        pickle.dump(tokenizer, f)
    print(f"  Tokenizer saved : {tok_path}")

    X, y = create_sequences(lines, tokenizer, SEQ_LEN)

    print(f"\n{'='*52}")
    print(f"STEP 4: MODEL  (Transformer decoder, GPT-style)")
    print(f"{'='*52}")
    model = build_model(
        vocab_size = actual_vocab, seq_len = SEQ_LEN, embed_dim = EMBED_DIM,
        num_heads  = NUM_HEADS, num_layers = NUM_LAYERS, ff_dim = FF_DIM,
        dropout    = DROPOUT_RATE,
    )
    model.compile(
        optimizer = tf.keras.optimizers.AdamW(learning_rate=0.001, weight_decay=1e-4, clipnorm=1.0),
        loss      = 'sparse_categorical_crossentropy',
        metrics   = ['accuracy']
    )
    model.summary()
    print(f"\n  Parameters   : {model.count_params():,}")

    print(f"\n{'='*52}")
    print(f"STEP 5: TRAINING")
    print(f"{'='*52}")
    print(f"  Sequences    : {len(X):,}")
    print(f"  Vocab size   : {actual_vocab:,}")
    print(f"  Seq length   : {SEQ_LEN}")
    print(f"  Heads/Layers : {NUM_HEADS} heads, {NUM_LAYERS} layers")
    print(f"  Max epochs   : {EPOCHS}  (EarlyStopping patience=5)")

    history = model.fit(
        X, y, batch_size=BATCH_SIZE, epochs=EPOCHS,
        validation_split=VALIDATION_SPLIT,
        callbacks=get_callbacks(SAVE_DIR), verbose=1,
    )

    model_path = os.path.join(SAVE_DIR, 'best_model.keras')
    model.save(model_path)

    cfg = {
        'vocab_size': actual_vocab, 'seq_len': SEQ_LEN, 'embed_dim': EMBED_DIM,
        'num_heads': NUM_HEADS, 'num_layers': NUM_LAYERS, 'ff_dim': FF_DIM,
    }
    cfg_path = os.path.join(SAVE_DIR, 'model_config.json')
    with open(cfg_path, 'w') as f:
        json.dump(cfg, f, indent=2)

    plot_history(history, SAVE_DIR)
    inference_demo(model, tokenizer, SEQ_LEN)

    best_acc   = max(history.history['val_accuracy'])
    best_loss  = min(history.history['val_loss'])
    perplexity = np.exp(best_loss)
    epochs_run = len(history.history['loss'])

    print(f"\n{'='*52}")
    print(f"TRAINING COMPLETE")
    print(f"{'='*52}")
    print(f"  Epochs run      : {epochs_run}/{EPOCHS}")
    print(f"  Best val loss   : {best_loss:.4f}")
    print(f"  Best val acc    : {best_acc*100:.2f}%")
    print(f"  Perplexity      : {perplexity:.2f}")
    print(f"  Random chance   : {1/actual_vocab*100:.4f}%")

    try:
        from google.colab import files
        files.download(model_path)
        files.download(tok_path)
        files.download(cfg_path)
        print(f"\n✓ Downloads started!")
    except Exception:
        print(f"\n  Manual download: Files panel → {SAVE_DIR}")


main()